site_name: Informácie o TIBER, DORA, TLPT a red teamingu.
site_url: https://tiber.sk
site_description: ""

theme:
    name: 'material'
    language: sk
    features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true

nav:
  - Čo je TIBER-EU?: tiber-eu.md
  - blog: blog/index.md
  - O nás: o_nás.md


plugins:
  - search
  - roamlinks
  - privacy
  - blog:
      archive: true
      categories: true
      pagination: true
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

extra:
  generator: false
#  alternate:
#    - name: Slovensky
#      link: /
#      lang: sk
#    - name: English
#      link: /en/
#      lang: en

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
