authors:
  richard_kellner:
    name: Richard Kellner
    description: "I am DevSecOps person, focusing on object-oriented programming in Python, and a lot of Linux administration (containers and servers)."
    avatar: "https://avatars.githubusercontent.com/u/1180686?v=4&size=64" 
    slug: richard-kellner
    url: https://tiber.sk

